// Generated by CoffeeScript 1.7.1
(function() {
  var food, foods, func, kids, lel, lol, _i, _len;

  foods = ['banana', 'apple', 'cherry'];

  for (_i = 0, _len = foods.length; _i < _len; _i++) {
    food = foods[_i];
    if (food !== 'banana') {
      console.log(food);
    }
  }

  lol = true;

  lel = false;

  if (lol || lel) {
    console.log('rly');
  }

  func = function(msg) {
    return console.log(msg);
  };

  func('MSG');

  kids = {
    brother: {
      name: "Max",
      age: 11
    },
    sister: {
      name: "Ida",
      age: 9
    }
  };

  lol = {
    brother: {
      name: 'rly',
      age: 100
    },
    sister: {
      name: 'lol'
    }
  };

  console.log(lol.sister.name);

}).call(this);

//# sourceMappingURL=first-script.map
